# HTTP 服务配置
http:
  api:
    # 监听主机
    host: localhost
    # 服务监听的端口
    port: 23333
# bukkit 端配置
bukkit:
  # bukkit 端地址, 端口不可省略
  client:
    - localhost:23334
  # 服务启用, 不需要的服务可以将 true 更改为 false,
  # 但是不要删除，以免后续找不到想开启的服务
  service:
    # 根路径, http://host:port/
    - rootPath:true
    - getAllOnlinePlayerAmount:true